/* ============ MyADHD — Bahasa Melayu ============
   Every string the public site shows, in Malay, keyed by the id that
   site.js stamps on the matching English element (a hash of the English
   HTML). English is never written here: it is harvested from the markup
   at load, so the HTML stays the only place English lives. `{icon}` is
   where an arrow-icon sits inside a link; site.js puts the original back.

   THIS IS NOT A TRANSLATION. It is the same thing said again by someone
   who speaks Malay — `awak`, short sentences, no DBP register — and it
   will not line up clause for clause with the English. The rules, the
   word bank and the checklist are in docs/bahasa-melayu-voice.md; read
   them before adding a string, and keep the legal pages and the medical
   disclaimer formal where they already are.

   Written for this site on 2026-09-12, rewritten in voice 2026-09-13.
   The ASRS questions are elsewhere (test.js) and carry their own note
   about translation vs instrument: they get no voice pass. */
window.MYADHD_MS = {
  strings: {
  "ie58f7f8": "Aktiviti",
  "i3ffb811": "Tentang kami",
  "i2c2cd2a": "Testimoni",
  "i4832e45": "Hubungi kami",
  "ib226a42": "Apa yang kami tawarkan: <a href=\"/self-check\">Semakan kendiri</a> · <a href=\"/blog\">Blog</a> · <a href=\"/habits\">Tabiat</a> · <a href=\"/reading-list\">Senarai bacaan</a> · <a href=\"/tools\">Alatan</a>",
  "ia9dfd3a": "SEMAKAN KENDIRI",
  "i00e97c0": "BLOG",
  "i6307583": "TABIAT",
  "ib4fca04": "SENARAI BACAAN",
  "i9d0e510": "ALATAN",
  "i1d4d87b": "Buat semakan kendiri",
  "i45406d3": "Mula di sini.",
  "i5abc5dd": "Kalau ada yang terasa macam awak, itu belum tentu <span class=\"adhd-word\">ADHD</span>. Tapi mungkin ia berbaloi untuk awak tahu.",
  "i6fcbae3": "Sepuluh minit dan satu log masuk Google. Percuma. Ia takkan diagnos awak &mdash; ia cuma beritahu sama ada perbualan itu berbaloi.",
  "ia8ac426": "Buat semakan kendiri {icon}",
  "i3ace36a": "{icon} Lihat semua yang kami ada",
  "ide9430f": "Alat untuk mula &mdash; bukan rawatan, terapi, atau nasihat perubatan.",
  "i08a28d8": "Apa yang kami tawarkan.",
  "i3c58793": "Apa Yang Kami Tawarkan",
  "i05157ae": "Nak faham <span class=\"adhd-word\">ADHD</span> tak sepatutnya perlukan surat rujukan dan tunggu enam bulan. Semua di bawah ni percuma, bahasa senang, dan dibuat untuk orang Malaysia.",
  "i375a488": "Mula Dengan Semakan Kendiri Percuma",
  "ie3b5bf4": "Berdasarkan soal selidik saringan yang digunakan perkhidmatan kesihatan Malaysia",
  "ia903da2": "Sepuluh minit dan satu log masuk Google. Percuma. Jawab jujur, dan awak dapat gambaran jelas sama ada ciri-ciri awak cukup kuat untuk pergi buat penilaian penuh.",
  "i35c7d01": "Ini alat saringan, bukan diagnosis &mdash; yang boleh bagi diagnosis cuma pakar psikiatri atau ahli psikologi klinikal. Tapi ia beritahu awak sama ada perbualan itu berbaloi, dan ia bagi awak sesuatu yang kukuh untuk dibawa ke temu janji &mdash; bukan sekadar &ldquo;doktor, saya rasa saya ada masalah fokus.&rdquo;",
  "i22ee5b3": "{icon} Buat semakan kendiri",
  "ie81a7c0": "Kenali <span class=\"adhd-word\">ADHD</span> Yang Sebenar",
  "ic800ad6": "Artikel, penerangan, dan pengalaman sebenar &mdash; dalam Bahasa Inggeris dan Bahasa Malaysia",
  "i15be1dc": "Kebanyakan apa yang orang Malaysia tahu tentang <span class=\"adhd-word\">ADHD</span> datang dari kandungan luar &mdash; sistem kesihatan orang, sekolah orang, jangkaan keluarga orang. Kami tak macam tu.",
  "icceb581": "Kami tulis tentang <span class=\"adhd-word\">ADHD</span> macam mana ia muncul di sini: sesi KPI, kenduri keluarga, sistem sekolah, perkahwinan, rasa malu. Laluan diagnosis di Malaysia. Apa yang rawatan tu sebenarnya libatkan. Apa nak cakap dengan mak ayah yang fikir ini semua alasan.",
  "i637156e": "{icon} Baca blog",
  "i4e2cf72": "Bina Sistem Yang Sejalan Dengan Otak Awak",
  "i2679c89": "Tabiat yang boleh dibuat, bukan nasihat kuatkan semangat",
  "iecbfe17": "Awak dah pun cuba lebih keras. Tak jadi &mdash; bukan sebab awak lemah, tapi sebab &ldquo;fokus je lah&rdquo; bukan strategi untuk otak yang memang tak makan ayat tu.",
  "ifea22d0": "Bahagian ni tentang apa yang betul-betul membantu: struktur di luar kepala, body doubling, memecah tembok kerja yang awak asyik elak, mengurus masa bila masa tak terasa nyata, dan habiskan hari tanpa bateri kosong menjelang 3 petang. Perubahan kecil yang boleh diuji. Mula dengan satu.",
  "i2125929": "{icon} Teroka tabiat",
  "id2640b3": "Buku Yang Berbaloi Masa Awak",
  "ia7fd532": "Dipilih, jujur, dan realistik tentang tumpuan awak",
  "i2ea04e4": "Rak <span class=\"adhd-word\">ADHD</span> sesak, dan banyak yang bunyi je. Kami syorkan apa yang kami betul-betul dah baca, dengan nota buku itu untuk siapa &mdash; orang dewasa yang baru didiagnos, ibu bapa, pasangan, atau orang yang nak sains dia je.",
  "i6084309": "Kalau ada versi audio, kami bagitahu. Kalau buku tu panjang dan berulang-ulang, kami bagitahu juga.",
  "i3d1ca79": "{icon} Lihat senarai bacaan",
  "i8899c05": "Alatan Yang Meringankan Beban",
  "i807b8c9": "Aplikasi, pemasa, dan sistem yang ingat bagi pihak awak",
  "iafd634e": "Alat yang tepat tak baiki <span class=\"adhd-word\">ADHD</span>. Ia cuma angkat beban tu keluar dari kepala awak, letak kat benda yang tak lupa.",
  "ie4a2411": "Kami uji apa yang kami syorkan, dan kami bagitahu harganya, sama ada versi percuma dah cukup, dan &mdash; jujur &mdash; sama ada ia masih ada dalam telefon awak sebulan lagi.",
  "i24377e4": "{icon} Tengok alatan",
  "ibc98198": "Seterusnya",
  "id3c7ae2": "{icon} Blog",
  "i53ac30e": "Luah fikiran, ia balas balik. Tanpa akaun, tak payah set apa-apa, dan senarai awak kekal dalam peranti awak.",
  "i731361d": "Kosongkan kepala saya {icon}",
  "ib953849": "Apa yang kami tawarkan",
  "i050c897": "Semakan kendiri",
  "i0b9d2b2": "Blog",
  "i45ab397": "Tabiat",
  "id80f6ec": "Senarai bacaan",
  "i4fa8cc8": "Alatan",
  "ice21cc3": "Buka my.adhd",
  "i85773bc": "Tambah ke skrin utama",
  "i979e25d": "Sapa kami",
  "icf01481": "Privasi",
  "ia55a275": "Terma",
  "i0974f3c": "Tentang kami.",
  "ie71b270": "Awak niat nak mula tugasan tu tiga minggu lepas. Awak lambat walaupun keluar awal. Awak potong cakap orang tengah-tengah ayat, dan rasa bersalah setiap kali. Fikiran awak ada di enam tempat serentak &mdash; tak satu pun tempat yang awak perlukan.",
  "i658d1f4": "Di Malaysia, kita ada nama untuk ini. Malas. Tak fokus. Tak matang. Tak reti jaga barang.",
  "ia275e17": "Yang kita jarang sebut ialah nama yang satu lagi: <span class=\"adhd-word\">ADHD</span>.",
  "i9030eaa": "Itulah jurang yang MyADHD wujud untuk rapatkan. Terlalu ramai orang Malaysia membesar dengan percaya yang mereka cuai, malas, atau tak cukup berusaha &mdash; sedangkan apa yang mereka hadap sebenarnya ialah otak yang berfungsi lain, dalam sebuah negara yang tak pernah diajar untuk kenal benda tu. Kesedaran di sini masih nipis. Diagnosis lambat dan mahal. <span class=\"adhd-word\">ADHD</span> dewasa, lagi la jarang disebut.",
  "i4282922": "Kami di sini untuk ubah benda tu. Kami tunjuk rupa sebenar <span class=\"adhd-word\">ADHD</span> dalam hidup harian orang Malaysia &mdash; di sekolah, di tempat kerja, dalam perkahwinan, dalam keluarga. Kami tunjuk jalan ke penilaian yang betul, bukan teka-teka. Dan kami bina satu ruang untuk awak berhenti tanya apa yang tak kena dengan saya, dan mula tanya soalan yang lebih baik.",
  "i2c7e465": "<b>Aiman Hafidz</b>Pengasas, MyADHD",
  "i618d739": "{icon} Testimoni",
  "i63d9984": "Testimoni.",
  "iadcf2ff": "Apa kata mereka",
  "if49db87": "Tiga orang, dalam kata-kata mereka sendiri.",
  "i7aa0695": "“Akhirnya saya faham diri saya.”",
  "i94fa9fb": "“Didiagnos dengan <span class=\"adhd-word\">ADHD</span> ubah cara saya tengok seluruh hidup saya. Dulu saya ingat saya malas, cuai, atau tak reti urus masa. Bila saya faham macam mana otak saya berfungsi, semuanya mula masuk akal. Saya berhenti salahkan diri, dan mula cari sistem yang betul-betul jalan untuk saya.”",
  "if5bf968": "Wanita, 27",
  "ibede2c2": "“Saya berhenti melawan diri sendiri.”",
  "ieb027db": "“Sebelum saya tahu saya ada <span class=\"adhd-word\">ADHD</span>, saya akan buat senarai kerja dan rasa bersemangat beberapa jam… lepas tu hilang arah terus. Saya ingat ada benda tak kena dengan saya. Belajar pasal <span class=\"adhd-word\">ADHD</span> tolong saya faham kenapa nak mula dan nak tukar kerja rasa berat sangat. Sekarang saya pecahkan kerja jadi langkah-langkah kecil, dan sebenarnya lagi banyak yang siap &mdash; tanpa hukum diri sendiri.”",
  "icec4824": "Lelaki, 31",
  "if90de1d": "“Hubungan saya bertambah baik.”",
  "ia9bd396": "“<span class=\"adhd-word\">ADHD</span> tolong saya faham kenapa kadang-kadang saya terlupa balas mesej, hilang arah tengah berbual, atau tiba-tiba hiperfokus pada satu benda. Dulu saya ingat saya ni kawan dan pasangan yang teruk. Sekarang saya berkomunikasi lebih baik, guna peringatan, dan kenal corak diri sendiri. Bezanya besar &mdash; lagi besar dari yang saya sangka &mdash; dalam hubungan saya.”",
  "i5bfc963": "Wanita, 25",
  "i037d6d2": "{icon} Hubungi kami",
  "i3ae58c9": "Hubungi kami.",
  "ibd3b8f5": "Sesuatu beta tu cuma sebagus maklum balas yang ia dapat. Bagitahu kami apa yang rosak.",
  "i84add5b": "E-mel",
  "ic98c528": "Berbaloi ditulis",
  "i2e2e6b5": "Tugasan yang tersusun salah, dan apa yang awak taip sebenarnya",
  "i00357e4": "Apa-apa yang buat senarai awak hilang, atau nampak macam nak hilang",
  "i5c9bc44": "Perkataan dalam aplikasi yang buat awak berhenti dan baca dua kali",
  "i2514534": "Benda yang buat awak asyik buka aplikasi lain",
  "id4ad5f6": "Takde sistem tiket di sebalik ni. E-mel sampai kepada manusia.",
  "ie778b83": "{icon} Aktiviti",
  "i51c59b0": "Apa yang kami tawarkan &middot; 02.",
  "i6e3d0e4": "Blog.",
  "ie468aa8": "<span class=\"adhd-word\">ADHD</span> macam mana ia muncul di sini.",
  "i118a91d": "Tarikh &middot; Penulis",
  "i6a4d21c": "Kiriman pertama akan ada di sini.",
  "i1f69308": "Setiap kad bawa tarikh, penulis dan petikan &mdash; blog ni ditulis bersama pelajar dan penyelidik yang mengkaji <span class=\"adhd-word\">ADHD</span>.",
  "i89b86ab": "Bahasa",
  "if26d03d": "Bahasa Inggeris dan Bahasa Malaysia.",
  "ic314b7d": "Suis di atas hidup bila ada kiriman dalam dua-dua bahasa.",
  "idfa4de0": "{icon} Tabiat",
  "i0d4a4ff": "Apa yang kami tawarkan &middot; 03.",
  "ibe98bb8": "Tabiat.",
  "i1c3b092": "Apa yang benar-benar membantu.",
  "i406e342": "Di luar kepala",
  "i5bb2191": "Ini bukan masalah ingatan. Tahu apa nak buat dan buat benda itu dua kerja yang berbeza, dan yang kedua itulah yang selalu tersasar.",
  "i4912970": "Jadi berhenti minta diri awak ingat. Letak benda itu di tempat awak akan terserempak dengannya. Satu senarai, bukan lima. Nota di pintu, bukan dalam app yang awak kena ingat nak buka.",
  "i093f4b9": "Ada orang lain",
  "i4aeed46": "Buat kerja sebelah orang lain buat permulaan jadi lebih senang. Dalam bilik yang sama, atas panggilan, atau orang tak dikenali dalam video.",
  "i5614637": "Kami cakap terus terang: kajiannya nipis dan menunjuk ke dua arah. Yang baiknya, ia percuma untuk dicuba, dan satu sesi dah cukup untuk beritahu awak sama ada ia menjadi.",
  "i47e55ea": "Saat pertama",
  "iddc3cb5": "Bukan awak elak kerja itu. Awak tersekat pada saat pertamanya.",
  "i222fd23": "Kecilkan saat itu sampai takde apa nak dibantah &mdash; buka app, cari nombor itu, letak kasut di pintu.",
  "ibf4f4d1": "Lepas itu tetapkan bila dan di mana. Rancangan yang ada waktu akan bertahan sehari; yang kata nanti tak akan.",
  "i960d36b": "Masa yang nampak",
  "ia090a1b": "Sejam tak rasa macam sejam, dan takde disiplin yang boleh betulkan itu.",
  "i7d8c386": "Letak masa di tempat awak boleh tengok ia susut: jam yang ada jarum, pemasa yang kosong perlahan-lahan. Lepas itu catat berapa lama benda sebenarnya ambil. Kebanyakan orang jumpa yang silap itu anggaran, bukan kelajuan.",
  "i06bd39f": "Jam terbaik awak",
  "ie4d1e46": "Lesu petang selalunya bermula malam sebelumnya. Kalau malam awak lewat, yang patut dipegang tetap ialah waktu awak bangun, bukan waktu awak tidur.",
  "i1437805": "Dan belanjakan jam terbaik awak pada kerja yang memerlukannya. Kerja pentadbiran pukul 10 pagi membelanjakan jam paling tajam yang awak ada pada benda paling murah yang awak buat.",
  "ibc6a49c": "Struktur di luar kepala",
  "ic0c5f87": "Body doubling",
  "iaa0fcb2": "Memecah tembok kerja yang awak asyik elak",
  "iebf358a": "Mengurus masa bila masa tak terasa nyata",
  "iaaab651": "Habiskan hari tanpa bateri kosong menjelang 3 petang",
  "ia6bfd85": "Perubahan kecil yang boleh diuji. Mula dengan satu.",
  "ic911107": "{icon} Senarai bacaan",
  "ifc1a6c1": "Apa yang kami tawarkan &middot; 04.",
  "i43060e9": "Rak buku.",
  "id09bac2": "Yang kami betul-betul dah baca je.",
  "i09324c2": "Untuk siapa",
  "i8f99c7f": "Buku pertama akan ada di sini.",
  "ib1edcf3": "Setiap kad bagitahu buku itu untuk siapa, dan sama ada ada versi audio.",
  "i0f74a27": "{icon} Alatan",
  "i7068fcf": "Kosongkan kepala saya",
  "i7b0ab73": "Apa yang kami tawarkan &middot; 05.",
  "i9ce7222": "Macam mana rasanya.",
  "i527d231": "Sibuk sepanjang hari. Takde apa yang siap.",
  "i95f8063": "Bukan awak tak peduli. Awak peduli semua benda serentak &mdash; sama je dengan tak boleh pilih &mdash; dan menjelang petang, satu-satunya benda yang awak ada untuk ditunjuk ialah betapa penatnya awak.",
  "i718697a": "Itu bukan kelemahan peribadi. Itu senarai yang belum disusun.",
  "iefbcc91": "Masalahnya.",
  "i3b9ab85": "Takde apa yang ditulis, jadi semuanya kena pegang &mdash; serentak, sepanjang hari, dalam satu-satunya tempat yang memang dah sibuk.",
  "i6ca8fee": "Temu janji doktor gigi teringat pukul 11 malam, atas katil.",
  "ib2ba447": "Awak buka laptop nak buat satu benda, tutup lepas buat benda lain.",
  "i6385af3": "Enam benda rasa sama mendesak, jadi tak satu pun bermula.",
  "ic585cd6": "Benda yang awak elak seminggu tu, empat minit je siap.",
  "i87adff4": "Awak tulis senarai, lepas tu awak hilangkan senarai tu.",
  "i5489801": "Bila awak dah putus nak buat yang mana dulu, sejam dah lesap.",
  "id0167c3": "Apa yang sebenarnya berlaku.",
  "i4004dab": "Dari kepala yang terlalu penuh, kepada satu benda yang awak boleh mula.",
  "i4a66d14": "Semuanya",
  "i2f3e778": "Semuanya masuk dalam satu kotak",
  "i0eb9424": "Satu ruang. Takde kategori nak pilih, takde susunan yang kena betul &mdash; taip, atau tekan mikrofon dan sebut je. Kusut tu memang input yang betul.",
  "ife73d79": "Tenang",
  "id0f9c4c": "Ia balik dalam keadaan tersusun dan bertempoh",
  "ic0175ae": "Kerja, pentadbiran, duit, kesihatan, rumah, sosial, urusan. Paling mendesak dulu, lepas tu yang paling singkat &mdash; momentum kalahkan kesempurnaan &mdash; dan setiap tugasan bawa anggaran dalam minit. Bila dah ditulis dan dah diletak, ia berhenti minta untuk diingat.",
  "i952f375": "Mula",
  "i2747af5": "Setiap tugasan dibuka dengan langkah pertama",
  "ided158b": "Satu langkah, cukup kecil sampai nak tolak pun rasa mengarut. Ia datang dalam warna oren &mdash; satu-satunya warna yang aplikasi ni simpan untuk satu makna: mula di sini.",
  "i5ad9b38": "Aktiviti.",
  "i72ed8e4": "Apa yang awak betul-betul boleh buat dalamnya",
  "idda735f": "Enam benda, dan takde skrin tetapan antara awak dengan mana-mana satu.",
  "ie648f01": "Luahkan semuanya",
  "i1c57691": "Satu ruang teks. Takde struktur, takde kategori, takde susunan yang kena betul. Kusut tu memang input yang betul, dan luahan baharu tambah pada senarai awak, bukan ganti.",
  "iae44077": "Tekan untuk bercakap",
  "i37b35dc": "Corong yang sama, tanpa perlu taip. Tekan mikrofon, sebut, lepas. Rakaman tu wujud sampai transkrip balik je &mdash; ia tak pernah disimpan, dan apa yang masuk dalam kotak ialah teks yang boleh awak sunting.",
  "ifc8ee38": "Biar ia susun",
  "if40dbdc": "Timbunan tu balik jadi tugasan: tajuk ditulis semula, minit yang realistik, kos tenaga, tahap mendesak, dan langkah pertama yang cukup kecil sampai nak tolak pun rasa bodoh.",
  "iea7ed95": "Baca empat senarai, bukan tujuh",
  "i32ebaf6": "Lewat, Hari ini, Akan datang, Belum bertarikh &mdash; ikut urutan hari tu mendesak awak. Kategori ialah penapis di atas, bukan bentuk halaman, dan tajuk yang kosong tak pernah dilukis.",
  "ie6674b4": "Hantar yang bertarikh ke Google Calendar",
  "i8e5cf58": "Mati sampai awak hidupkan, dan dihadkan supaya ia tak boleh sentuh kalendar sedia ada awak. Ia buat kalendar sendiri, dan itu yang ia jaga supaya sentiasa selari.",
  "i07cf224": "Simpan di semua peranti &mdash; atau tak payah",
  "i75bf3f5": "Log masuk tu pilihan, dan ia datang kemudian. Pelayar awak tetap jadi sumber kebenaran; akaun cuma bagi salinan kedua supaya senarai yang sama muncul dalam telefon awak.",
  "i0d85f96": "Kenapa satu kotak boleh membantu.",
  "i9fcd86b": "Empat benda yang betul tentang kepala yang terlalu penuh.",
  "i369b507": "Dapatan 01",
  "ic8edc22": "Menulisnya menenangkan kepala awak &mdash; sebelum awak siap pun",
  "i9312ace": "Kerja yang belum siap akan terus ketuk bahu awak, menyesakkan apa sahaja yang awak cuba beri perhatian. Tulis dengan tepat apa yang awak akan buat seterusnya, dan ketukan tu berhenti di situ &mdash; walaupun kerja tu sendiri masih menunggu.",
  "icafbb12": "Dapatan 02",
  "ia981778": "Kepala awak cuma mampu pegang lebih kurang empat benda serentak",
  "i23aff6b": "Itu had ingatan jangka pendek, sebaik awak berhenti mengulangnya dalam kepala. Hari yang sibuk ada lebih daripada empat benda, jadi senarai tu perlukan tempat tinggal yang bukan diri awak.",
  "if520c9b": "Dapatan 03",
  "id36595a": "Awak tak nampak masa berlalu &mdash; jadi teka awak selalu tersasar",
  "i0345b48": "Orang <span class=\"adhd-word\">ADHD</span> memang selalu tersasar bila nak agak berapa lama sesuatu ambil masa &mdash; bukan malas, cuma buta jam. Sebab tu setiap tugasan ditulis minitnya, bukan diteka.",
  "iba5d69d": "Dapatan 04",
  "i38fb59e": "Satu langkah kecil dah cukup untuk mula",
  "icc954d9": "Rancangan paling menjadi bila ia sebut dengan tepat apa yang kena buat dulu. Jadi setiap tugasan datang dengan satu langkah kecil yang dah dipilih &mdash; cukup kecil sampai nak mula rasa senang.",
  "if4a3ede": "Tiada satu pun daripada ni rawatan. Ini apa yang kajian cakap tentang mengeluarkan sesuatu dari kepala awak, masuk ke dalam satu rancangan.",
  "ia1673f2": "Sepanjang hari, kepala awak yang jadi senarai tu.",
  "i834af51": "Bagi ia tempat lain untuk tinggal. Satu kotak masuk, senarai balik tersusun &mdash; dengan langkah pertama dah dipilih.",
  "i257fa99": "Tanpa akaun",
  "i10fc385": "Tak payah set apa-apa",
  "i24b5de4": "Senarai awak kekal dalam peranti awak",
  "i8e07898": "{icon} Tentang kami",
  "ibelieve": "APA YANG KAMI PERCAYA",
  "iee8de84": "Terlalu ramai orang Malaysia membesar dengan percaya yang mereka cuai, malas, atau tak cukup berusaha.",

  /* ---- /soon, the page every app link goes to while the app is
     shut. Delete this block and the page with it when it opens. ---- */
  "i37d6026": "Sedang dibaiki.",
  "i1535579": "Apl ni tutup sementara kami bina semula",
  "i60e5da7": "my.adhd &mdash; tempat awak buang semua dalam kepala tu &mdash; tutup buat sementara. Kami tengah kerjakan dia, dia belum cukup elok untuk sesiapa bergantung padanya, dan biar dia terbuka dalam keadaan macam tu lagi teruk.",
  "ic628885": "Takde apa-apa yang dipadam",
  "i5e94b61": "Senarai awak ada kat tempat awak tinggalkan dia. Apa yang ada dalam telefon awak, masih ada. Apa yang dah masuk akaun, masih dalam akaun. Tutup pintu bukan bermakna bilik tu dikosongkan.",
  "i84bb5f7": "Semakan kendiri masih buka",
  "i20cb131": "Saringan ASRS-v1.1 tu bukan sebahagian daripada apl, jadi takde apa yang berubah. Sepuluh minit, percuma, dan keputusannya kekal milik awak.",
  "i2d660c9": "Belum ada tarikh",
  "ia0b2c05": "Lagi baik kami cakap macam tu daripada pilih satu hari Jumaat lepas tu tak jadi. Bila dia buka, dia buka kat sini juga, alamat yang sama, dan setiap butang yang bawa awak ke halaman ni akan jalan balik.",
  "i1dc3f38": "Nak kami bagitahu bila dia buka?",
  "i916ff37": "Hantar satu baris ke alamat kat bawah tu, nanti kami balas bila dia dah buka. Takde senarai, takde borang, takde newsletter &mdash; cuma orang, dan satu jawapan.",
  "i3bc2e39": "Tempat buang isi kepala tu tutup buat masa ni. Semakan kendiri tak tutup, dan itu bahagian yang bagi awak jawapan.",
  "i5b065b3": "Kalau fokus, mula benda, atau habiskan benda tu sebabnya awak datang sini, saringan tu memang bahagian yang lagi berguna pun."
},
  aria: {
  "197101e": "Buka menu",
  "4bfc194": "Halaman seterusnya",
  "949ec14": "Kembali ke muka depan",
  "12f3e1f": "Laman utama MyADHD",
  "1de9b5a": "Baca seterusnya",
  "b953849": "Apa yang kami tawarkan",
  "89b86ab": "Bahasa"
},
  scene: [
  "Terlalu ramai orang Malaysia membesar dengan percaya yang mereka cuai, malas, atau tak cukup berusaha.",
  "Sedangkan apa yang mereka hadap sebenarnya ialah otak yang berfungsi lain.",
  "Kesedaran di sini masih nipis. Diagnosis lambat dan mahal.",
  "ADHD dewasa, lagi la jarang disebut.",
  "Kami tunjuk jalan ke penilaian yang betul, bukan teka-teka."
]
};
