/* ============ MyADHD — Bahasa Melayu ============
   Every string the public site shows, in Malay, keyed by the id that
   site.js stamps on the matching English element (a hash of the English
   HTML). English is never written here: it is harvested from the markup
   at load, so the HTML stays the only place English lives. `{icon}` is
   where an arrow-icon sits inside a link; site.js puts the original back.
   Written for this site on 2026-09-12; the ASRS questions are elsewhere
   (test.js) and carry their own note about translation vs instrument. */
window.MYADHD_MS = {
  strings: {
  "ie58f7f8": "Aktiviti",
  "i3ffb811": "Tentang kami",
  "i2c2cd2a": "Testimoni",
  "i4832e45": "Hubungi kami",
  "ib226a42": "Apa yang kami tawarkan: <a href=\"/self-check\">Semakan kendiri</a> · <a href=\"/blog\">Blog</a> · <a href=\"/habits\">Tabiat</a> · <a href=\"/reading-list\">Senarai bacaan</a> · <a href=\"/tools\">Alatan</a>",
  "ia9dfd3a": "SEMAKAN KENDIRI",
  "i00e97c0": "BLOG",
  "i6307583": "TABIAT",
  "ib4fca04": "SENARAI BACAAN",
  "i9d0e510": "ALATAN",
  "i1d4d87b": "Buat semakan kendiri",
  "i45406d3": "Mula di sini.",
  "i5abc5dd": "Jika ada yang terasa dekat, ia tidak bermakna anda mempunyai <span class=\"adhd-word\">ADHD</span>. Tetapi mungkin ia bermakna ia berbaloi untuk diketahui.",
  "i6fcbae3": "Sepuluh minit, tanpa log masuk, tanpa kos. Ia tidak akan mendiagnosis anda &mdash; ia memberitahu sama ada perbualan itu berbaloi.",
  "ia8ac426": "Buat semakan kendiri {icon}",
  "i3ace36a": "{icon} Lihat semua yang kami tawarkan",
  "ide9430f": "Alat untuk bermula &mdash; bukan rawatan, terapi, atau nasihat perubatan.",
  "i08a28d8": "Apa yang kami tawarkan.",
  "i3c58793": "Apa Yang Kami Tawarkan",
  "i05157ae": "Memahami <span class=\"adhd-word\">ADHD</span> tidak sepatutnya memerlukan surat rujukan dan penantian enam bulan. Semua di bawah ini percuma, dalam bahasa yang mudah, dan dibina untuk rakyat Malaysia.",
  "i375a488": "Mulakan Dengan Semakan Kendiri Percuma",
  "ie3b5bf4": "Berdasarkan soal selidik saringan yang digunakan oleh perkhidmatan kesihatan Malaysia",
  "ia903da2": "Sepuluh minit, tanpa log masuk, tanpa kos. Jawab dengan jujur dan anda akan mendapat gambaran jelas sama ada ciri-ciri anda berada dalam julat yang wajar mendapat penilaian sewajarnya.",
  "i35c7d01": "Ini alat saringan, bukan diagnosis &mdash; hanya pakar psikiatri atau ahli psikologi klinikal boleh memberikannya. Tetapi ia memberitahu sama ada perbualan itu berbaloi, dan ia memberi anda sesuatu yang konkrit untuk dibawa ke temu janji, bukan sekadar &ldquo;doktor, saya rasa saya ada masalah fokus.&rdquo;",
  "i22ee5b3": "{icon} Buat semakan kendiri",
  "ie81a7c0": "Fahami Apa Sebenarnya <span class=\"adhd-word\">ADHD</span>",
  "ic800ad6": "Artikel, penerangan, dan pengalaman hidup &mdash; dalam Bahasa Inggeris dan Bahasa Malaysia",
  "i15be1dc": "Kebanyakan yang rakyat Malaysia tahu tentang <span class=\"adhd-word\">ADHD</span> datang daripada kandungan luar yang mengandaikan sistem kesihatan luar, sekolah luar, dan jangkaan keluarga luar. Kandungan kami tidak.",
  "icceb581": "Kami menulis tentang <span class=\"adhd-word\">ADHD</span> seperti yang muncul di sini: penilaian KPI, kenduri keluarga, sistem sekolah, perkahwinan, rasa malu. Laluan diagnosis di Malaysia. Apa yang rawatan sebenarnya libatkan. Apa yang perlu dikatakan kepada ibu bapa yang fikir ia hanya alasan.",
  "i637156e": "{icon} Baca blog",
  "i4e2cf72": "Bina Sistem Yang Sesuai Dengan Otak Anda",
  "i2679c89": "Tabiat praktikal, bukan nasihat kekuatan azam",
  "iecbfe17": "Anda sudah pun cuba lebih keras. Ia tidak berhasil &mdash; bukan kerana anda lemah, tetapi kerana &ldquo;fokus sajalah&rdquo; bukan strategi untuk otak yang tidak bertindak balas kepadanya.",
  "ifea22d0": "Bahagian ini merangkumi apa yang benar-benar membantu: struktur luaran, body doubling, meruntuhkan tembok tugasan yang anda asyik elakkan, mengurus masa apabila masa tidak terasa nyata, dan mengharungi hari tanpa kehabisan tenaga menjelang 3 petang. Perubahan kecil yang boleh diuji. Mulakan dengan satu.",
  "i2125929": "{icon} Teroka tabiat",
  "id2640b3": "Buku Yang Berbaloi Dibaca",
  "ia7fd532": "Dipilih, jujur, dan realistik tentang tempoh tumpuan",
  "i2ea04e4": "Rak <span class=\"adhd-word\">ADHD</span> penuh sesak dan banyak daripadanya hanya bising. Kami hanya mengesyorkan apa yang kami benar-benar baca, dengan nota untuk siapa setiap buku itu &mdash; dewasa yang baru didiagnosis, ibu bapa, pasangan, atau mereka yang sekadar mahukan sainsnya.",
  "i6084309": "Jika ada versi buku audio, kami akan sebutkan. Jika sesebuah buku itu panjang dan berulang-ulang, kami akan sebutkan itu juga.",
  "i3d1ca79": "{icon} Lihat senarai bacaan",
  "i8899c05": "Alatan Yang Meringankan Beban",
  "i807b8c9": "Aplikasi, pemasa, dan sistem yang mengingat untuk anda",
  "iafd634e": "Alat yang tepat tidak membaiki <span class=\"adhd-word\">ADHD</span>. Ia sekadar memindahkan usaha itu keluar dari kepala anda ke sesuatu yang tidak akan lupa.",
  "ie4a2411": "Kami menguji apa yang kami syorkan dan memberitahu kosnya, sama ada versi percuma sudah memadai, dan &mdash; secara jujur &mdash; sama ada ia masih akan ada di telefon anda sebulan lagi.",
  "i24377e4": "{icon} Layari alatan",
  "ibc98198": "Seterusnya",
  "id3c7ae2": "{icon} Blog",
  "i53ac30e": "Luahan fikiran yang membalas. Tanpa akaun, tiada yang perlu disediakan, dan senarai anda kekal di peranti anda.",
  "i731361d": "Lapangkan fikiran saya {icon}",
  "ib953849": "Apa yang kami tawarkan",
  "i050c897": "Semakan kendiri",
  "i0b9d2b2": "Blog",
  "i45ab397": "Tabiat",
  "id80f6ec": "Senarai bacaan",
  "i4fa8cc8": "Alatan",
  "ice21cc3": "Buka my.adhd",
  "i85773bc": "Tambah ke skrin utama",
  "i979e25d": "Sapa kami",
  "icf01481": "Privasi",
  "ia55a275": "Terma",
  "i0974f3c": "Tentang kami.",
  "ie71b270": "Anda berniat memulakan tugasan itu tiga minggu lalu. Anda lewat walaupun keluar awal. Anda mencelah orang di tengah ayat dan rasa bersalah setiap kali. Fikiran anda berada di enam tempat serentak, dan tiada satu pun tempat yang anda perlukan.",
  "i658d1f4": "Di Malaysia, kita ada nama untuk ini. Malas. Tak fokus. Tak matang. Tak reti jaga barang.",
  "ia275e17": "Kita jarang ada nama yang satu lagi untuknya: <span class=\"adhd-word\">ADHD</span>.",
  "i9030eaa": "Itulah jurang yang MyADHD wujud untuk rapatkan. Terlalu ramai rakyat Malaysia membesar dengan percaya bahawa mereka cuai, malas, atau sekadar tidak cukup berusaha &mdash; sedangkan apa yang sebenarnya mereka hadapi ialah otak yang berfungsi secara berbeza, dan sebuah negara yang belum diajar untuk mengenalinya. Kesedaran di sini masih nipis. Diagnosis lambat dan mahal. <span class=\"adhd-word\">ADHD</span> dewasa, khususnya, hampir tidak dibincangkan langsung.",
  "i4282922": "Kami di sini untuk mengubahnya. Kami berkongsi rupa sebenar <span class=\"adhd-word\">ADHD</span> dalam kehidupan seharian rakyat Malaysia &mdash; di sekolah, di tempat kerja, dalam perkahwinan, dalam keluarga. Kami membimbing orang ke arah penilaian sewajarnya, bukan tekaan. Dan kami membina ruang di mana anda akhirnya boleh berhenti bertanya apa yang tak kena dengan saya dan mula bertanya soalan yang lebih baik.",
  "i2c7e465": "<b>Aiman Hafidz</b>Pengasas, MyADHD",
  "i618d739": "{icon} Testimoni",
  "i63d9984": "Testimoni.",
  "iadcf2ff": "Apa kata mereka",
  "if49db87": "Tiga orang, dalam kata-kata mereka sendiri.",
  "i7aa0695": "“Akhirnya saya faham diri saya.”",
  "i94fa9fb": "“Didiagnosis dengan <span class=\"adhd-word\">ADHD</span> mengubah cara saya melihat seluruh hidup saya. Dulu saya fikir saya malas, cuai, atau sekadar tidak pandai mengurus masa. Sebaik saya faham cara otak saya berfungsi, semuanya mula masuk akal. Saya berhenti menyalahkan diri dan mula mencari sistem yang benar-benar berkesan untuk saya.”",
  "if5bf968": "Wanita, 27",
  "ibede2c2": "“Saya berhenti melawan diri sendiri.”",
  "ieb027db": "“Sebelum mengetahui <span class=\"adhd-word\">ADHD</span> saya, saya akan buat senarai tugasan dan rasa bersemangat untuk beberapa jam… kemudian hilang arah sepenuhnya. Saya fikir ada yang tak kena dengan saya. Mempelajari tentang <span class=\"adhd-word\">ADHD</span> membantu saya faham mengapa memulakan dan bertukar tugasan terasa begitu sukar. Kini saya pecahkan kerja kepada langkah lebih kecil, dan saya sebenarnya lebih banyak menyiapkan kerja tanpa menghukum diri.”",
  "icec4824": "Lelaki, 31",
  "if90de1d": "“Hubungan saya bertambah baik.”",
  "ia9bd396": "“<span class=\"adhd-word\">ADHD</span> membantu saya faham mengapa saya kadang-kadang lupa mesej, hilang arah semasa perbualan, atau tiba-tiba hiperfokus pada sesuatu. Dulu saya fikir saya kawan atau pasangan yang teruk. Kini saya berkomunikasi lebih baik, menggunakan peringatan, dan memahami corak diri saya sendiri. Ia membawa perbezaan yang mengejutkan besar dalam hubungan saya.”",
  "i5bfc963": "Wanita, 25",
  "i037d6d2": "{icon} Hubungi kami",
  "i3ae58c9": "Hubungi kami.",
  "ibd3b8f5": "Sesuatu beta hanya sebaik maklum balas yang diterimanya. Beritahu kami apa yang rosak.",
  "i84add5b": "E-mel",
  "ic98c528": "Berbaloi ditulis",
  "i2e2e6b5": "Tugasan yang tersilap disusun, dan apa yang sebenarnya anda taip",
  "i00357e4": "Apa-apa yang menghilangkan senarai anda, atau nampak seperti akan",
  "i5c9bc44": "Perkataan dalam antara muka yang membuat anda berhenti dan membacanya semula",
  "i2514534": "Perkara yang membuat anda asyik membuka aplikasi lain",
  "id4ad5f6": "Tiada sistem tiket di sebalik semua ini. E-mel sampai kepada seorang manusia.",
  "ie778b83": "{icon} Aktiviti",
  "i51c59b0": "Apa yang kami tawarkan &middot; 02.",
  "i6e3d0e4": "Blog.",
  "ie468aa8": "<span class=\"adhd-word\">ADHD</span> seperti yang muncul di sini.",
  "i118a91d": "Tarikh &middot; Penulis",
  "i6a4d21c": "Kiriman pertama akan berada di sini.",
  "i1f69308": "Setiap kad memuatkan tarikh, penulis dan petikan &mdash; blog ini akan ditulis bersama pelajar dan penyelidik yang mengkaji <span class=\"adhd-word\">ADHD</span>.",
  "i89b86ab": "Bahasa",
  "if26d03d": "Bahasa Inggeris dan Bahasa Malaysia.",
  "ic314b7d": "Suis di atas akan aktif apabila ada kiriman dalam kedua-duanya.",
  "idfa4de0": "{icon} Tabiat",
  "i0d4a4ff": "Apa yang kami tawarkan &middot; 03.",
  "ibe98bb8": "Tabiat.",
  "i1c3b092": "Apa yang benar-benar membantu.",
  "ibc6a49c": "Struktur luaran",
  "id66c43b": "Tabiat akan berada di sini.",
  "ic0c5f87": "Body doubling",
  "iaa0fcb2": "Meruntuhkan tembok tugasan yang anda asyik elakkan",
  "iebf358a": "Mengurus masa apabila masa tidak terasa nyata",
  "iaaab651": "Mengharungi hari tanpa kehabisan tenaga menjelang 3 petang",
  "ia6bfd85": "Perubahan kecil yang boleh diuji. Mulakan dengan satu.",
  "ic911107": "{icon} Senarai bacaan",
  "ifc1a6c1": "Apa yang kami tawarkan &middot; 04.",
  "i43060e9": "Rak buku.",
  "id09bac2": "Hanya apa yang kami benar-benar baca.",
  "i09324c2": "Untuk siapa",
  "i8f99c7f": "Buku pertama akan berada di sini.",
  "ib1edcf3": "Setiap kad menyatakan untuk siapa buku itu, dan sama ada versi buku audio wujud.",
  "i0f74a27": "{icon} Alatan",
  "i7068fcf": "Lapangkan fikiran saya",
  "i7b0ab73": "Apa yang kami tawarkan &middot; 05.",
  "i9ce7222": "Bagaimana rasanya.",
  "i527d231": "Sibuk sepanjang hari. Tiada yang siap.",
  "i95f8063": "Bukannya anda tidak peduli. Anda peduli tentang semuanya serentak, yang sama sahaja dengan tidak mampu memilih &mdash; dan menjelang petang satu-satunya perkara yang boleh anda tunjukkan ialah betapa penatnya anda.",
  "i718697a": "Itu bukan kelemahan peribadi. Itu senarai yang belum disusun.",
  "iefbcc91": "Masalahnya.",
  "i3b9ab85": "Tiada apa yang ditulis, jadi semuanya perlu dipegang &mdash; serentak, sepanjang hari, di satu-satunya tempat yang sudah pun sibuk.",
  "i6ca8fee": "Temu janji doktor gigi teringat pada 11 malam, di atas katil.",
  "ib2ba447": "Anda buka komputer riba untuk buat satu perkara dan tutup setelah membuat perkara lain.",
  "i6385af3": "Enam perkara terasa sama mendesak, jadi tiada satu pun yang bermula.",
  "ic585cd6": "Perkara yang anda elakkan selama seminggu mengambil masa empat minit.",
  "i87adff4": "Anda tulis senarai, kemudian anda hilangkan senarai itu.",
  "i5489801": "Sebaik anda memutuskan apa yang perlu dibuat dahulu, sejam sudah berlalu.",
  "id0167c3": "Apa yang sebenarnya berlaku.",
  "i4004dab": "Daripada kepala yang terlalu penuh kepada satu perkara yang boleh anda mulakan.",
  "i4a66d14": "Semuanya",
  "i2f3e778": "Semuanya masuk dalam satu kotak",
  "i0eb9424": "Satu ruangan. Tiada kategori untuk dipilih, tiada susunan yang perlu betul &mdash; taip, atau tekan mikrofon dan sebutkan. Kekusutan itulah input yang betul.",
  "ife73d79": "Tenang",
  "id0f9c4c": "Ia kembali tersusun dan bertempoh",
  "ic0175ae": "Kerja, pentadbiran, wang, kesihatan, rumah, sosial, urusan. Paling mendesak dahulu, kemudian yang paling singkat &mdash; momentum mengatasi kesempurnaan &mdash; dan setiap tugasan membawa anggaran dalam minit. Setelah ditulis dan diletakkan, ia berhenti meminta untuk diingati.",
  "i952f375": "Mula",
  "i2747af5": "Setiap tugasan dibuka dengan langkah pertama",
  "ided158b": "Satu langkah, cukup kecil sehingga menolaknya terasa mengarut. Ia tiba dalam warna oren &mdash; satu-satunya warna yang aplikasi ini simpan untuk satu makna, iaitu: mula di sini.",
  "i5ad9b38": "Aktiviti.",
  "i72ed8e4": "Apa yang sebenarnya boleh anda buat di dalamnya",
  "idda735f": "Enam perkara, dan tiada skrin tetapan di antara anda dan mana-mana daripadanya.",
  "ie648f01": "Luahkan semuanya",
  "i1c57691": "Satu ruang teks. Tiada struktur, tiada kategori, tiada susunan yang perlu betul. Kekusutan itulah input yang betul, dan luahan baharu menambah kepada senarai anda, bukan menggantikannya.",
  "iae44077": "Tekan untuk bercakap",
  "i37b35dc": "Corong yang sama tanpa perlu menaip. Tekan mikrofon, sebutkan, lepaskan. Rakaman itu wujud hanya sehingga transkrip kembali &mdash; ia tidak pernah disimpan, dan apa yang masuk ke kotak ialah teks yang boleh disunting.",
  "ifc8ee38": "Biar ia susun",
  "if40dbdc": "Timbunan itu kembali sebagai tugasan: tajuk yang ditulis semula, minit yang realistik, kos tenaga, tahap mendesak, dan langkah pertama yang cukup kecil sehingga menolaknya terasa bodoh.",
  "iea7ed95": "Baca empat senarai, bukan tujuh",
  "i32ebaf6": "Lewat, Hari ini, Akan datang, Belum bertarikh &mdash; mengikut urutan hari itu mendesak anda. Kategori ialah penapis di bahagian atas, bukan bentuk halaman, dan tajuk yang kosong tidak pernah dilukis.",
  "ie6674b4": "Hantar yang bertarikh ke Google Calendar",
  "i8e5cf58": "Mati sehingga anda menghidupkannya, dan dihadkan supaya ia tidak boleh menyentuh kalendar yang sedia ada. Ia membuat kalendarnya sendiri dan memastikan itu sentiasa selari.",
  "i07cf224": "Simpan di setiap peranti &mdash; atau tidak",
  "i75bf3f5": "Log masuk adalah pilihan dan datang kemudian. Pelayar anda kekal sebagai sumber kebenaran apa pun; akaun hanya memberi salinan kedua supaya senarai yang sama muncul di telefon anda.",
  "i0d85f96": "Mengapa sebuah kotak membantu.",
  "i9fcd86b": "Empat perkara yang benar tentang kepala yang terlalu penuh.",
  "i369b507": "Dapatan 01",
  "ic8edc22": "Menulisnya menenangkan fikiran anda &mdash; bahkan sebelum anda selesai",
  "i9312ace": "Tugasan yang belum selesai terus mengetuk bahu anda, menyesakkan apa sahaja yang anda alihkan perhatian kepadanya. Tuliskan dengan tepat apa yang akan anda buat seterusnya dan ketukan itu berhenti di situ &mdash; sedangkan tugasan itu sendiri masih menunggu.",
  "icafbb12": "Dapatan 02",
  "ia981778": "Kepala anda hanya mampu memegang kira-kira empat perkara serentak",
  "i23aff6b": "Itulah had ingatan jangka pendek sebaik anda berhenti mengulanginya. Hari yang sibuk mempunyai lebih daripada empat perkara, jadi senarai itu perlukan tempat tinggal yang bukan diri anda.",
  "if520c9b": "Dapatan 03",
  "id36595a": "Anda tidak nampak masa berlalu &mdash; jadi anda tersilap teka",
  "i0345b48": "Orang dengan <span class=\"adhd-word\">ADHD</span> sentiasa tersasar apabila menilai berapa lama sesuatu mengambil masa &mdash; bukan malas, cuma buta terhadap jam. Jadi setiap tugasan ditulis minitnya, bukan diteka.",
  "iba5d69d": "Dapatan 04",
  "i38fb59e": "Satu langkah kecil sudah cukup untuk bermula",
  "icc954d9": "Sesuatu rancangan paling berkesan apabila ia menyatakan dengan tepat apa yang perlu dibuat dahulu. Jadi setiap tugasan datang dengan satu langkah kecil yang sudah dipilih &mdash; cukup kecil sehingga memulakannya terasa mudah.",
  "if4a3ede": "Tiada satu pun daripada ini rawatan. Ia apa yang kajian katakan tentang mengeluarkan sesuatu dari kepala anda ke dalam sebuah rancangan.",
  "ia1673f2": "Sepanjang hari, kepala anda telah menjadi senarai itu.",
  "i834af51": "Berikan ia tempat lain untuk tinggal. Satu kotak masuk, senarai tersusun kembali &mdash; dengan langkah pertama sudah dipilih.",
  "i257fa99": "Tanpa akaun",
  "i10fc385": "Tiada yang perlu disediakan",
  "i24b5de4": "Senarai anda kekal di peranti anda",
  "i8e07898": "{icon} Tentang kami",
  "ibelieve": "APA YANG KAMI PERCAYA",
  "iee8de84": "Terlalu ramai rakyat Malaysia membesar dengan percaya bahawa mereka cuai, malas, atau sekadar tidak cukup berusaha."
},
  aria: {
  "197101e": "Buka menu",
  "4bfc194": "Halaman seterusnya",
  "949ec14": "Kembali ke muka depan",
  "12f3e1f": "Laman utama MyADHD",
  "1de9b5a": "Baca seterusnya",
  "b953849": "Apa yang kami tawarkan",
  "89b86ab": "Bahasa"
},
  scene: [
  "Terlalu ramai rakyat Malaysia membesar dengan percaya bahawa mereka cuai, malas, atau sekadar tidak cukup berusaha.",
  "Apa yang sebenarnya mereka hadapi ialah otak yang berfungsi secara berbeza.",
  "Kesedaran di sini masih nipis. Diagnosis lambat dan mahal.",
  "ADHD dewasa, khususnya, hampir tidak dibincangkan langsung.",
  "Kami membimbing orang ke arah penilaian sewajarnya, bukan tekaan."
]
};
